import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jose David Gale Torre</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-secondary flex min-h-screen flex-col items-center justify-center">
        <div className="fixed top-0 flex h-14 w-full flex-row items-center  text-xl font-bold text-primary">
          <div className="flex h-14 w-1/5 cursor-pointer items-center justify-center border-b-2 border-r-2 border-solid border-primary">
            Jose Gale
          </div>
          <div className="flex h-14 w-3/5 items-center justify-center border-b-2 border-primary">
            <ul className="flex">
              <li className="ml-5 mr-5 cursor-pointer">About</li>
              <li className="ml-5 mr-5 cursor-pointer">Projects</li>
              <li className="ml-5 mr-5 cursor-pointer">Contact</li>
            </ul>
          </div>
          <div className="flex h-14 w-1/5 items-center justify-center border-b-2 border-l-2 border-primary">
            <ul className="flex ">
              <li>Honguito</li>
              <li>Acido</li>
              <li>Rehab</li>
            </ul>
          </div>
        </div>
      </main>
    </>
  );
}
